### ISSUE TITLE
Segfault on Windows 32bit during `unlocked_ssl_recv_into`

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabctools#91]
After the release of 4.0.0 we have gotten reports of the release failing to download for the 32bit Windows release.
That one was not included in the CI here, so we never caught it.
I added it now, and indeed, segfault:
https://github.com/sabnzbd/sabctools/actions/runs/4845980163/jobs/8635227344

I have no clue why...
Hoping you might know? @mnightingale @animetosho 

I added Python 3.8, since we use that for the 32bit release, but also tested the 32bit version of 3.11 and it also crashes:
https://github.com/sabnzbd/sabctools/actions/runs/4846003595/jobs/8635265868

**Comment by sanderjo** [comment]
```
tests\test_sparse.py ....                                                [ 84%]
Windows fatal exception: access violation
```
So test_space.py goes OK? And it fails in the next test, so test_unlocked_ssl.py?


So @Safihre, on Windows what is the output of `pytest --verbose -k test_unlocked_ssl.py` ?

FWIW: on Linux:


```
sander@zwart2204:~/git/sabctools$ pytest --verbose -k test_unlocked_ssl.py
======================================================================== test session starts =========================================================================
platform linux -- Python 3.10.6, pytest-7.2.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/sander/git/sabctools, configfile: pytest.ini
plugins: mock-3.10.0, tavern-2.0.5, pyfakefs-5.1.0, httpserver-1.0.6, httpbin-1.0.2, asyncio-0.20.3, flaky-3.7.0
asyncio: mode=strict
collected 53 items / 45 deselected / 8 selected                                                                                                                      

tests/test_unlocked_ssl.py::test_openssl_linked PASSED                                                                                                         [ 12%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_not_a_socket_fails PASSED                                                                              [ 25%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_not_a_buffer_fails PASSED                                                                              [ 37%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_response PASSED                                                                                        [ 50%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_bulk_response PASSED                                                                                   [ 62%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_blocking_socket_fails PASSED                                                                           [ 75%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_full_buffer_fails PASSED                                                                               [ 87%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_ref_counts_unchanged PASSED                                                                            [100%]
```

**Comment by Safihre** [comment]
Good point.
It fails here:
```
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_not_a_socket_fails PASSED                                                                                                                                                                                                                              [ 88%] 
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_not_a_buffer_fails PASSED                                                                                                                                                                                                                              [ 90%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_response
```

**Comment by mnightingale** [comment]
Error is basically its trying to access memory it shouldn't.

I noticed other changes with uses of Py_ssize_t were made, so could it be an issue with https://github.com/sabnzbd/sabctools/blob/5cca997442d6c3eaba200f439e2fa9f1aac8eb33/src/unlocked_ssl.cc#L238

I can setup a 32 bit VM to investigate further.

**Comment by sanderjo** [comment]
Could it be a 32bit thing, so also on Linux 32 bit (old Raspi's)? I tried on a 32 bit raspi, and I get warnings ... not sure if that is bad?

```
pi@raspberrypi:~/git/sabctools $ pytest-3 --verbose -k test_unlocked_ssl.py
======================================================================== test session starts =========================================================================
platform linux -- Python 3.9.2, pytest-7.3.1, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/pi/git/sabctools
configfile: pytest.ini
collected 53 items / 45 deselected / 8 selected                                                                                                                      

tests/test_unlocked_ssl.py::test_openssl_linked PASSED                                                                                                         [ 12%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_not_a_socket_fails PASSED                                                                              [ 25%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_not_a_buffer_fails PASSED                                                                              [ 37%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_response PASSED                                                                                        [ 50%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_bulk_response PASSED                                                                                   [ 62%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_blocking_socket_fails PASSED                                                                           [ 75%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_full_buffer_fails PASSED                                                                               [ 87%]
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_ref_counts_unchanged PASSED                                                                            [100%]

========================================================================== warnings summary ==========================================================================
tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_response
  /home/pi/.local/lib/python3.9/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-3
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
      self.run()
    File "/home/pi/git/sabctools/tests/test_unlocked_ssl.py", line 210, in run
      conn, addr = self.sock.accept()
    File "/usr/lib/python3.9/socket.py", line 293, in accept
      fd, addr = self._accept()
  socket.timeout: timed out
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/test_unlocked_ssl.py::test_unlocked_ssl_recv_into_ref_counts_unchanged
  /home/pi/.local/lib/python3.9/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-11
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
      self.run()
    File "/home/pi/git/sabctools/tests/test_unlocked_ssl.py", line 210, in run
      conn, addr = self.sock.accept()
    File "/usr/lib/python3.9/socket.py", line 293, in accept
      fd, addr = self._accept()
  socket.timeout: timed out
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================== 8 passed, 45 deselected, 2 warnings in 13.84s ============================================================
pi@raspberrypi:~/git/sabctools $ 


```

**Comment by animetosho** [comment]
Oops, I assumed that DLL calls on Windows was generally `stdcall`, but I guess that only applies to the system API.

Try changing [this line](https://github.com/sabnzbd/sabctools/blob/5cca997442d6c3eaba200f439e2fa9f1aac8eb33/src/unlocked_ssl.h#L29) to [this one](https://github.com/sabnzbd/sabctools/blob/5cca997442d6c3eaba200f439e2fa9f1aac8eb33/src/unlocked_ssl.h#L34) (this does make the `SABCTOOLS_DLL_CALL` define useless, so you could also remove it completely).

**Comment by Safihre** [comment]
I'm not sure I understand how this is would fix it? How is 32bit different in the dll call? :)

**Comment by Safihre** [comment]
So indeed it works, but I still don't know why 😁
https://github.com/sabnzbd/sabctools/actions/runs/4849254458

**Comment by animetosho** [comment]
> I'm not sure I understand how this is would fix it? How is 32bit different in the dll call? :)

`stdcall` only exists in 32-bit Windows, hence effectively ignored in 64-bit Windows (there's only one valid calling convention there).

The complication arises because [32-bit Windows has multiple calling conventions](https://en.wikipedia.org/wiki/X86_calling_conventions#List_of_x86_calling_conventions), so the correct one needs to be used.  
In this case, the DLL functions should be called using the `cdecl` convention; assuming `stdcall` causes the stack to be positioned incorrectly after the call, causing the segfault.

**Comment by Safihre** [comment]
Thanks for teaching me something new again and the quick fix!

**Comment by mnightingale** [comment]
Well that explains it, I narrowed it down to the DLL calls yesterday but couldn't understand why it was failing or returning odd results since the arguments seemed correct to me.

I've tested the fixed branch on a Windows 10 32-bit VM without issue.
